### ISSUE TITLE
test problem

### ISSUE THREAD

**Issue by gudianyue** [ronghuaiyang/arcface-pytorch#47]
when i run python test.py. the problem will come:
D:\anaconda\envs\pytorch\python.exe "D:/py program/arcface-pytorch-master/test.py"
read ./data/Datasets/lfw/lfw-align-128\Abel_Pacheco/Abel_Pacheco_0001.jpg error
Traceback (most recent call last):
  File "D:/py program/arcface-pytorch-master/test.py", line 172, in <module>
    lfw_test(model, img_paths, identity_list, opt.lfw_test_list, opt.test_batch_size)
  File "D:/py program/arcface-pytorch-master/test.py", line 143, in lfw_test
    features, cnt = get_featurs(model, img_paths, batch_size=batch_size)
  File "D:/py program/arcface-pytorch-master/test.py", line 62, in get_featurs
    if images.shape[0] % batch_size == 0 or i == len(test_list) - 1:
AttributeError: 'NoneType' object has no attribute 'shape'

Process finished with exit code 1
why?

**Comment by mengxia1994** [comment]
I met the same problem, i tested step by step and finally found the wrong place.
It is an absolute path problem. 
The lfw_root in config.py shouldn't begin with '/data/...', it should be, e.g. '/root/arcface-pytorch/data/...' or easier, remove the '/' in front of data/...

In addition, when i run it. Several import error happened, i add a '.' before the py file names and it works. Seems that the __init__.py doesn't work.

**Comment by xuexiaoxiaohu** [comment]
I met the other problem ,FileNotFoundError: [Errno 2] No such file or directory: 'checkpoints/resnet18_110.pth'
in the config.py 
    train_root = '/data/Datasets/webface/CASIA-maxpy-clean-crop-144/'
    train_list = '/data/Datasets/webface/train_data_13938.txt'
    val_list = '/data/Datasets/webface/val_data_13938.txt'

    test_root = '/data1/Datasets/anti-spoofing/test/data_align_256'
    test_list = 'test.txt'

    lfw_root = '/media/li/Elements/lfw-align-128'
    lfw_test_list = '/home/li/download/shixi/gcn-decoder/arcface-pytorch-master/lfw_test_pair.txt'

    checkpoints_path = 'checkpoints'
    load_model_path = '/home/li/download/shixi/gcn-decoder/arcface-pytorch-master/models/resnet18.pth'
    test_model_path = 'checkpoints/resnet18_110.pth'
  I have no Datasets files and how to run the test.py
thank you

**Comment by Youqi970124** [comment]
I change the path but I still have this problem.
Could someone help me
This is my e-mail: youqi860124@alum.ccu.edu.tw

Thank you very much.
