### ISSUE TITLE
cannot import name config from 'config' (unknown location)

### ISSUE THREAD

**Issue by komentra** [ronghuaiyang/arcface-pytorch#92]
Follow the instructions exactly & made sure it was installed to c:/fairgame, but anytime I get to step of running amazon.bat I end up getting this:

`Traceback (most recent call last):
  File "app.py", line 60, in <module>
    from cli import cli
  File "C:\fairgame\cli\cli.py", line 32, in <module>
    from common.globalconfig import AMAZON_CREDENTIAL_FILE, GlobalConfig
  File "C:\fairgame\common\globalconfig.py", line 21, in <module>
    from config import config as Cfg
ImportError: cannot import name 'config' from 'config' (unknown location)`

**Comment by Mei0211** [comment]
just import in train.py like this：from config.config import Config

**Comment by yychentw** [comment]
This is because the folder `config` and the file `config.py` have the same name. This ambiguity causes the problem.
You can rename the folder `config` to `configs` and make sure you modify the corresponding import statement like this: `from configs import Config`.

**Comment by majmal7** [comment]
@yychentw , 
how to fix this "ImportError: cannot import name 'config' from 'jax.config'"?
